import{a as v,S as w,i as a}from"./assets/vendor-C4-ZuMk8.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))d(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&d(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function d(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();const L="46831660-d1aa08367accf9e9e1755dc5b",E="https://pixabay.com/api/",P=15;async function f(r,o=1){try{const s=await v.get(E,{params:{key:L,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:P}});return s.data.hits.length===0?{images:[],totalHits:0}:{images:s.data.hits,totalHits:s.data.totalHits}}catch(s){throw console.error("Error fetching images:",s),s}}function m(r){const o=document.querySelector(".gallery"),s=r.map(({webformatURL:d,largeImageURL:e,tags:t,likes:i,views:p,comments:b,downloads:S})=>`
        <div class="photo-card">
            <a href="${e}" data-lightbox="image" data-title="${t}">
                <img src="${d}" alt="${t}" loading="lazy" />
            </a>
            <div class="info">
                <p><b>Likes:</b> ${i}</p>
                <p><b>Views:</b> ${p}</p>
                <p><b>Comments:</b> ${b}</p>
                <p><b>Downloads:</b> ${S}</p>
            </div>
        </div>
    `).join("");o.insertAdjacentHTML("beforeend",s)}let n=1,u="",y=0;const g=document.querySelector(".search-form"),c=document.querySelector(".load-more-btn"),l=document.querySelector(".loader"),q=document.querySelector(".gallery"),h=new w(".gallery a",{captionsData:"alt",captionDelay:250});g.addEventListener("submit",H);c.addEventListener("click",I);async function H(r){if(r.preventDefault(),u=g.elements.query.value.trim(),!u){a.error({title:"Error",message:"Please enter a search term."});return}n=1,c.style.display="none",l.style.display="block";try{const{images:o,totalHits:s}=await f(u,n);if(y=s,q.innerHTML="",o.length===0){a.info({title:"Info",message:"No images matching your search query. Try again!"});return}m(o),h.refresh(),l.style.display="none",n*15<y?c.style.display="block":a.info({title:"Info",message:"You've reached the end of the results."})}catch{a.error({title:"Error",message:"Something went wrong. Please try again."})}finally{l.style.display="none"}}async function I(){l.style.display="block",n+=1;try{const{images:r}=await f(u,n);if(r.length===0){a.info({title:"Info",message:"We're sorry, but you've reached the end of search results."}),c.style.display="none";return}m(r),h.refresh(),setTimeout($,100),n*15>=y&&(c.style.display="none",a.info({title:"Info",message:"We're sorry, but you've reached the end of search results."}))}catch{a.error({title:"Error",message:"Something went wrong. Please try again."})}finally{l.style.display="none"}}function $(){const r=document.querySelector(".gallery .photo-card");if(r){const o=r.getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
