import{a as w,i,S as v}from"./assets/vendor-C4-ZuMk8.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))d(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&d(s)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function d(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();const E="46831660-d1aa08367accf9e9e1755dc5b",P="https://pixabay.com/api/",q=15;async function m(t,o=1){try{const n=await w.get(P,{params:{key:E,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:q}});return n.data.hits.length===0?{images:[],totalHits:0}:{images:n.data.hits,totalHits:n.data.totalHits}}catch(n){throw console.error("Error fetching images:",n),n}}function g(t){const o=document.querySelector(".gallery"),n=t.map(({webformatURL:d,largeImageURL:e,tags:r,likes:s,views:b,comments:L,downloads:S})=>`
        <div class="photo-card">
            <a href="${e}" data-lightbox="image" data-title="${r}">
                <img src="${d}" alt="${r}" loading="lazy" />
            </a>
            <div class="info">
                <p><b>Likes:</b> ${s}</p>
                <p><b>Views:</b> ${b}</p>
                <p><b>Comments:</b> ${L}</p>
                <p><b>Downloads:</b> ${S}</p>
            </div>
        </div>
    `).join("");o.insertAdjacentHTML("beforeend",n)}let a=1,u="",y=0;const p=document.querySelector(".search-form"),c=document.querySelector(".load-more-btn"),l=document.querySelector(".loader"),f=document.querySelector(".gallery");p.addEventListener("submit",H);c.addEventListener("click",$);async function H(t){if(t.preventDefault(),u=p.elements.query.value.trim(),!u){i.error({title:"Error",message:"Please enter a search term."});return}a=1,c.style.display="none",l.style.display="block";try{const{images:o,totalHits:n}=await m(u,a);if(y=n,o.length===0){f.innerHTML="",i.info({title:"Info",message:"No images matching your search query. Try again!"});return}f.innerHTML="",g(o),h(),l.style.display="none",a*15<y&&(c.style.display="block")}catch{i.error({title:"Error",message:"Something went wrong. Please try again."})}finally{l.style.display="none"}}async function $(){l.style.display="block",a+=1;try{const{images:t}=await m(u,a);if(t.length===0){i.info({title:"Info",message:"We're sorry, but you've reached the end of search results."}),c.style.display="none";return}g(t),h(),setTimeout(x,100),a*15>=y&&(c.style.display="none")}catch{i.error({title:"Error",message:"Something went wrong. Please try again."})}finally{l.style.display="none"}}function x(){const t=document.querySelector(".gallery .photo-card");if(t){const o=t.getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"})}}function h(){new v(".gallery a",{captionsData:"alt",captionDelay:250}).refresh()}
//# sourceMappingURL=index.js.map
